services:
  mysqldb:
    container_name: mysqldb
    image: mariadb
    restart: always
    ports:
      - "3307:3306"
    environment:
      MARIADB_DATABASE: compagnie
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - mariadb_data:/var/lib/mysql

  ollama:
    container_name: ollama
    image: ollama/ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  app:
    container_name: app
    build: .
    restart: always
    ports:
      - "9090:8082"
    depends_on:
      - mysqldb
      - ollama
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
      OLLAMA_BASE_URL: http://ollama:11434

volumes:
  mariadb_data:
  ollama_data: